---
# tasks file for roles/elk-centos
- name: Installing java
  yum:
    name: java-1.8.0-openjdk
    state: present

- name: Adding gpg key
  become: yes
  command: sudo rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: Adding elastic rpm repo
  copy:
    src: elasticsearch.repo
    dest: /etc/yum.repos.d/

- name: Updating centos
  dnf:
    update_cache: yes

- name: Installing elasticsearch
  dnf:
    name: elasticsearch
    state: present

- name: Installing kibana
  dnf:
    name: kibana
    state: present

- name: Installing filebeat
  yum:
    name: filebeat
    state: present

- name: Installing logstash
  become: yes
  dnf:
    name: logstash
    state: latest
