---
# tasks file for roles/ubuntu/install-vsftpd
- name: Installing vsftpd and services
  apt:
    name:
      - vsftpd
      - ufw
    state: present
    update_cache: yes

- name: Starting vsftpd
  service:
    name: vsftpd
    state: started
    enabled: yes
