---
# tasks file for roles/centos/install-vsftpd
- name: Installing vsftpd
  yum:
    name: vsftpd
    state: present
    update_cache: yes

- name: Starting vsftpd
  service:
    name: vsftpd
    state: started
    enabled: yes

