---
# tasks file for roles/centos-vsftpd
- name: Installing vsftpd
  yum:
    name: vsftpd
    state: present
    update_cache: yes

- name: Stopping firewall
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: Creating ftp user
  user:
    name: eugene
    password: $6$AlF.SqvQXGjsrlRP$xmr3lCR.wqL/jT4S3hYPD01LRrzpL5cFCXnvhVP5ycR2rImS.ldRk6cyhbUh2ZnE3kbGvTEPnCm9K28OvYHtM1
    comment: "Eugene's FTP"

- name: Adding DenyUser
  lineinfile:
    path: /etc/ssh/sshd_config
    line: "DenyUsers eugene"
  register: sshd_config

- name: Restarting sshd
  service:
    name: sshd
    state: restarted
  when: sshd_config.changed

- name: Creating FTP folder
  file:
    path: /home/eugene/ftp
    state: directory
    owner: eugene
    group: eugene
    mode: '0555'

- name: Creating ftp file
  file:
    path: /home/eugene/ftp/files
    state: directory
    owner: eugene
    group: eugene

- name: Adding /etc/vsftpd.conf
  copy:
    src: vsftpd.conf
    dest: /etc/vsftpd.conf
  register: vsftpd_config

- name: Restarting vsftpd
  service:
    name: vsftpd
    state: restarted
  when: vsftpd_config.changed
